import uuid
from typing import Protocol

from src.domain.user.entities import EmailVerificationToken, PasswordResetToken, RefreshToken, User


class UserRepository(Protocol):
    def get_by_id(self, user_id: uuid.UUID) -> User | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def get_by_google_sub(self, sub: str) -> User | None: ...

    def add(self, user: User) -> User: ...

    def update(self, user: User) -> User: ...


class RefreshTokenRepository(Protocol):
    def add(self, token: RefreshToken) -> RefreshToken: ...

    def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...

    def revoke(self, token_id: uuid.UUID, replaced_by_id: uuid.UUID | None = None) -> None: ...

    def revoke_family(self, family_id: uuid.UUID) -> None: ...

    def revoke_all_for_user(self, user_id: uuid.UUID) -> None: ...


class EmailVerificationTokenRepository(Protocol):
    def add(self, token: EmailVerificationToken) -> EmailVerificationToken: ...

    def get_by_hash(self, token_hash: str) -> EmailVerificationToken | None: ...

    def mark_used(self, token_id: uuid.UUID) -> None: ...


class PasswordResetTokenRepository(Protocol):
    def add(self, token: PasswordResetToken) -> PasswordResetToken: ...

    def get_by_hash(self, token_hash: str) -> PasswordResetToken | None: ...

    def mark_used(self, token_id: uuid.UUID) -> None: ...
