import uuid
from typing import Protocol

from src.domain.candidate.entities import Candidate, Resume


class CandidateRepository(Protocol):
    def get_by_id(self, candidate_id: uuid.UUID) -> Candidate | None: ...

    def get_by_user_id(self, user_id: uuid.UUID) -> Candidate | None: ...

    def add(self, candidate: Candidate) -> Candidate: ...

    def update(self, candidate: Candidate) -> Candidate: ...


class ResumeRepository(Protocol):
    def add(self, resume: Resume) -> Resume: ...

    def get_by_id(self, resume_id: uuid.UUID) -> Resume | None: ...

    def list_by_candidate(self, candidate_id: uuid.UUID) -> list[Resume]: ...

    def get_by_content_hash(self, candidate_id: uuid.UUID, content_hash: str) -> Resume | None: ...

    def get_latest_version(self, candidate_id: uuid.UUID) -> int:
        """Returns the highest existing version number for this candidate, or 0 if none."""
        ...

    def update(self, resume: Resume) -> Resume: ...
