import uuid
from typing import Protocol

from src.domain.job.entities import Job, JobVersion


class JobRepository(Protocol):
    def get_by_id(self, job_id: uuid.UUID) -> Job | None: ...

    def list_by_company(self, company_id: uuid.UUID) -> list[Job]: ...

    def add(self, job: Job) -> Job: ...

    def update(self, job: Job) -> Job: ...

    def delete(self, job_id: uuid.UUID) -> None: ...


class JobVersionRepository(Protocol):
    def add(self, version: JobVersion) -> JobVersion: ...

    def list_by_job(self, job_id: uuid.UUID) -> list[JobVersion]: ...
