import uuid
from typing import Protocol

from src.domain.company.entities import Company, CompanyInvite, CompanyMember


class CompanyRepository(Protocol):
    def get_by_id(self, company_id: uuid.UUID) -> Company | None: ...

    def get_by_slug(self, slug: str) -> Company | None: ...

    def add(self, company: Company) -> Company: ...

    def update(self, company: Company) -> Company: ...

    def add_member(self, member: CompanyMember) -> CompanyMember: ...

    def get_member(self, company_id: uuid.UUID, user_id: uuid.UUID) -> CompanyMember | None: ...

    def list_members(self, company_id: uuid.UUID) -> list[CompanyMember]: ...

    def add_invite(self, invite: CompanyInvite) -> CompanyInvite: ...

    def get_invite_by_hash(self, token_hash: str) -> CompanyInvite | None: ...

    def mark_invite_accepted(self, invite_id: uuid.UUID) -> None: ...
